### ISSUE TITLE
有没有中文医疗的预训练模型，bert, xlnet etc.？

### ISSUE THREAD

**Issue by crazyofapple** [GanjinZero/awesome_Chinese_medical_NLP#1]
企业开源的或者github开源的？英文有biobert

**Comment by GanjinZero** [comment]
目前没有公开的，我其实正在训练这个

**Comment by crazyofapple** [comment]
之前有万方或者一些书籍的语料，但是因为计算资源等原因，未能训练。希望您训练出来共享一下，最好开源。。。

**Comment by GanjinZero** [comment]
https://github.com/GanjinZero/ChineseEHRBert

**Comment by crazyofapple** [comment]
嗯嗯，不错。有开源模型的打算吗？

**Comment by GanjinZero** [comment]
目前没有，以后看数据提供方的意愿（毕竟涉及病例数据）

**Comment by knowleton** [comment]
能和您请教下这方面的数据在哪里获取吗 @GanjinZero

**Comment by GanjinZero** [comment]
> 能和您请教下这方面的数据在哪里获取吗 @GanjinZero

数据是和医院合作的，非公开数据

**Comment by foreverwith** [comment]
想请教一下您的ChineseEHRBert模型数据量大概是多少呢，以及数据来源（粗略的那种，病例数据多少，文献数据多少这种）方便告知吗，非常感谢 @GanjinZero

**Comment by GanjinZero** [comment]
> 想请教一下您的ChineseEHRBert模型数据量大概是多少呢，以及数据来源（粗略的那种，病例数据多少，文献数据多少这种）方便告知吗，非常感谢 @GanjinZero

100G+ 全部来自病例
