### ISSUE TITLE
自己开源了一个生物医学领域的词向量，欢迎引用

### ISSUE THREAD

**Issue by WENGSYX** [GanjinZero/awesome_Chinese_medical_NLP#4]
因为网络上找不到中文医学领域的词向量，所以我搜集了网络上医学文献，医患对话，维基百科之类的中文医学语料，整理了一下总共1.6G，使用这份语料训练了一个生物医学领域的词向量，欢迎引用。https://github.com/WENGSYX/Chinese-Word2vec-Medicine

**Comment by GanjinZero** [comment]
欢迎提交pull request，或者我帮你直接一加
